astring = "Hello world!"
print(astring.index("o"))
print(astring.count("l"))
print(astring[3:7])
print(astring[3:7:2])
print(astring[::-2])
print(astring.upper())
print(astring.lower())
print(astring.startswith("H"))
print(astring.endswith("!"))
afewwords=astring.split(" ")
print(afewwords)
afewwords=astring.split("o")
print(afewwords)
